name: Get Citation Data for New template

on: 
 page_build: 
 schedule:
  - cron:  '0 8 * * *'
 workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
    - name: Run
      run: |
        cd ./google_scholar_crawler
        pip3 install -r requirements.txt
        python --version
        pip3 list
        echo "开始运行 main.py"
        python3 main.py
        cd ./results
        git init
        git config --local user.name "${GITHUB_ACTOR}"
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git add *.json
        git commit -m "Updated Citation Data"
        git push "${remote_repo}" HEAD:google_scholar_data --force
      env: 
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}

    - name: Trigger Deploy on new2 branch
        # 只有上面的步骤全部显示“绿色对勾（Success）”，这一步才会运行
        # 如果上面 git push 挂了，这一步会被自动 Skip（跳过）
      run: gh workflow run deploy.yml --ref new2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
